[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "openai_api_mock"
version = "0.1.0"
description = "A fast api based mock of the openai api."
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
keywords = ["openai api", "fast api", "LLM"]
authors = [
  {name = "Sander Hummerich", email = "sander.hummerich@gmx.de" }
]
maintainers = [
  {name = "Sander Hummerich", email = "sander.hummerich@gmx.de" }
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
  "fastapi",
  "lorem-text",
]

[project.scripts]
sample = "sample:main"
